docs:
  categorize_library: true
  categorize_verify: false
  html: false
  toc: false
plugins:
- jemoji
- jekyll-remote-theme
remote_theme: rsk0315/minima
theme: jekyll-theme-minimal

title: Yuri3's Code Library
author: Yuri3
description: Some Code Template Just for Fun.