author: Yuri3
description: Some Code Template Just for Fun.
docs:
  categorize_library: true
  categorize_verify: false
  html: false
  toc: false
plugins:
- jemoji
- jekyll-remote-theme
theme: jekyll-theme-minimal
title: Yuri3's Code Library
